CXX = g++ -c
CXXFLAGS = -O3
LDFLAGS = 
OBJS = ../../../obj/

sequenceUtils: sequenceUtils.cpp sequenceUtils.h
	$(CXX) $(CXXFLAGS) $(LDFLAGS) sequenceUtils.cpp -o $(OBJS)sequenceUtils.o

clean:
	rm $(OBJS) sequenceUtils.o
	rm sequenceUtils.o