name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y libbz2-dev liblzma-dev zlib1g-dev
    - name: Compile and test Bedtools
      run: make -j8 && make test
    - name: Compile static binary
      run:  make -j8 static
    - uses: actions/upload-artifact@v4
      with:
          name: bedtools.static
          path: bin/bedtools.static
